query getMovieByID($id: ID!){
	Movie(movieId: $id) {
    title
    year
    runtime
    poster
    imdbRating
    movieId
    plot
    similarMovies (first: 3) {
      title
      year
      runtime
      poster
      imdbRating
      movieId
    }
  }
}
