query getRecommendedMovies($id: ID!, $limit: Int!, $offset: Int!){
	recommended: User(userId: $id) {
    recommendedMovies(first: $limit, offset: $offset) {
      title
      year
      runtime
      poster
      imdbRating
      movieId
    }
  }

}